# DhanHQ API credentials
CLIENT_ID = "YOUR_CLIENT_ID"
ACCESS_TOKEN = "YOUR_ACCESS_TOKEN"

# Trading mode
LIVE_TRADING = False

# Index to trade
INDEX_TO_TRADE = "NIFTY_50" # NIFTY_50, BANKNIFTY, SENSEX

# Backtesting parameters
BACKTEST_FROM_DATE = "2024-01-01"
BACKTEST_TO_DATE = "2024-01-31"

# Strategy parameters
BB_LENGTH = 5
BB_STD = 2.0
RSI_LENGTH = 14
RSI_OVERBOUGHT = 60
RSI_OVERSOLD = 40
TRAIL_SL_PERCENT = 0.05
STRIKE_DIFFERENCE = {
    "NIFTY_50": 50,
    "BANKNIFTY": 100,
    "SENSEX": 100
}
RISK_FREE_RATE = 0.05
VOLATILITY = 0.2
